[phases.install]
cmds = ["npm install --include=dev --no-audit --no-fund"]

[phases.build]
cmds = [
  "npm run prisma:generate --workspace api",
  "npm run build --workspace api"
]

[start]
cmd = "npm run start:prod --workspace api"
